import { useState } from 'react';
import { DollarSign, Download, Edit2, Save, X, TrendingUp, CreditCard, FileText } from 'lucide-react';
import { useHRMS } from '../context/HRMSContext';
import Badge from '../components/ui/Badge';
import Avatar from '../components/ui/Avatar';
import Modal from '../components/ui/Modal';

export default function Payroll() {
  const { state, actions } = useHRMS();
  const isAdmin = state.viewingRole === 'admin';
  const userId = state.currentUser?.id;
  const [selectedEmployeeId, setSelectedEmployeeId] = useState(userId);
  const [editPayrollModal, setEditPayrollModal] = useState({ open: false, userId: null });
  const [editForm, setEditForm] = useState({});
  const [editLoading, setEditLoading] = useState(false);
  const [paySlipModal, setPaySlipModal] = useState({ open: false, period: null, userId: null });

  const employees = state.users.filter(u => u.role !== 'admin' || u.id === userId);
  const targetId = isAdmin ? selectedEmployeeId : userId;
  const targetUser = state.users.find(u => u.id === targetId);
  const targetProfile = state.profiles[targetId];
  // Use payroll from shared state (so admin edits are immediately visible to employee)
  const payroll = state.payroll[targetId];
  // Fallback payroll data to ensure safe access
  const payrollData = payroll || { baseSalary: 0, hra: 0, medical: 0, transport: 0, tax: 0, pf: 0, netSalary: 0, currency: 'USD', payPeriod: 'Monthly' };
  const sym = '₹'; // Use INR consistently
  // Use pay slip history from shared state (populated for all users)
  const paySlips = (state.paySlipHistory || {})[targetId] || [
    { id: `ps-${targetId}-aug`, period: 'August 2026', paidOn: '2026-08-31', status: 'Processing' },
    { id: `ps-${targetId}-jul`, period: 'July 2026', paidOn: '2026-07-31', status: 'Paid' },
    { id: `ps-${targetId}-jun`, period: 'June 2026', paidOn: '2026-06-30', status: 'Paid' },
  ];

  const handleOpenEdit = (uid) => {
    const p = state.payroll[uid];
    setEditForm({ ...p });
    setEditPayrollModal({ open: true, userId: uid });
  };

  const handleSavePayroll = async () => {
    setEditLoading(true);
    const base = parseInt(editForm.baseSalary) || 0;
    const hra = parseInt(editForm.hra) || 0;
    const med = parseInt(editForm.medical) || 0;
    const trans = parseInt(editForm.transport) || 0;
    const tax = parseInt(editForm.tax) || 0;
    const pf = parseInt(editForm.pf) || 0;
    const net = base + hra + med + trans - tax - pf;
    await new Promise(r => setTimeout(r, 600));
    actions.updatePayroll(editPayrollModal.userId, { ...editForm, baseSalary: base, hra, medical: med, transport: trans, tax, pf, netSalary: net });
    setEditPayrollModal({ open: false, userId: null });
    setEditLoading(false);
  };

  const handleDownloadPaySlip = (period, uid) => {
    const u = state.users.find(x => x.id === uid);
    const p = state.profiles[uid];
    const pay = state.payroll[uid];
    const s = pay?.currency === 'INR' ? '₹' : pay?.currency === 'GBP' ? '£' : pay?.currency === 'KRW' ? '₩' : '$';
    const content = `
NEXORA HR — PAY SLIP
========================
Employee: ${u?.name}
Employee ID: ${u?.empId}
Department: ${p?.department || 'N/A'}
Job Title: ${p?.jobTitle || 'N/A'}
Pay Period: ${period}
Currency: ${pay?.currency}

EARNINGS
--------
Base Salary:         ${s}${pay?.baseSalary?.toLocaleString()}
HRA:                 ${s}${pay?.hra?.toLocaleString()}
Medical Allowance:   ${s}${pay?.medical?.toLocaleString()}
Transport Allowance: ${s}${pay?.transport?.toLocaleString()}
                     ─────────────
TOTAL EARNINGS:      ${s}${(pay?.baseSalary + pay?.hra + pay?.medical + pay?.transport).toLocaleString()}

DEDUCTIONS
----------
Income Tax:          ${s}${pay?.tax?.toLocaleString()}
Provident Fund:      ${s}${pay?.pf?.toLocaleString()}
                     ─────────────
TOTAL DEDUCTIONS:    ${s}${(pay?.tax + pay?.pf).toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━
NET SALARY:          ${s}${pay?.netSalary?.toLocaleString()}
━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Nexora HR • Smart Human Resource Management System
    `.trim();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PaySlip-${u?.name?.replace(' ', '_')}-${period.replace(' ', '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    actions.showToast({ type: 'success', title: 'Pay Slip Downloaded', message: `${period} pay slip downloaded.` });
  };

  

  return (
    <div>
      <div className="page-header">
        <div className="page-header-left">
          <h1 className="page-title">Payroll</h1>
          <p className="page-subtitle">{isAdmin ? 'Manage salary structures and view employee payroll' : 'Your salary breakdown and pay slip history'}</p>
        </div>
      </div>

      {/* Admin Employee Selector */}
      {isAdmin && (
        <div className="card" style={{ marginBottom: '1rem', padding: '1rem 1.5rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
            <span style={{ fontSize: '0.875rem', fontWeight: 500, color: 'var(--color-text-secondary)', whiteSpace: 'nowrap' }}>Select Employee:</span>
            <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
              {employees.map(emp => (
                <button
                  key={emp.id}
                  className={`btn btn-sm ${selectedEmployeeId === emp.id ? 'btn-primary' : 'btn-outline'}`}
                  onClick={() => setSelectedEmployeeId(emp.id)}
                  style={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}
                >
                  <Avatar name={emp.name} color={emp.avatarColor} />
                  {emp.name.split(' ')[0]}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Net Salary Banner */}
      <div style={{
        background: 'linear-gradient(135deg, var(--color-primary), #6D28D9)',
        borderRadius: 'var(--radius-xl)',
        padding: '2rem',
        color: 'white',
        marginBottom: '1rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: '1rem',
        position: 'relative',
        overflow: 'hidden',
      }}>
        <div style={{ position: 'absolute', width: 200, height: 200, borderRadius: '50%', background: 'rgba(255,255,255,0.05)', top: -80, right: -40 }} />
        <div style={{ position: 'relative', zIndex: 1 }}>
          {targetUser && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem' }}>
              <Avatar name={targetUser.name} color="rgba(255,255,255,0.3)" />
              <div>
                <div style={{ fontWeight: 600, fontSize: '0.9375rem' }}>{targetUser.name}</div>
                <div style={{ fontSize: '0.8125rem', opacity: 0.8 }}>{targetProfile?.jobTitle} · {targetProfile?.department}</div>
              </div>
            </div>
          )}
          <div style={{ fontSize: '0.875rem', opacity: 0.8, marginBottom: '0.375rem' }}>Net Monthly Salary ({payrollData.currency})</div>
          <div style={{ fontSize: '3rem', fontWeight: 800, letterSpacing: '-0.03em', lineHeight: 1 }}>
            {sym}{payrollData.netSalary.toLocaleString()}
          </div>
        </div>
        <div style={{ position: 'relative', zIndex: 1, display: 'flex', gap: '0.75rem', flexWrap: 'wrap' }}>
          <button
            className="btn"
            style={{ background: 'rgba(255,255,255,0.15)', color: 'white', border: '1px solid rgba(255,255,255,0.3)', backdropFilter: 'blur(4px)' }}
            onClick={() => setPaySlipModal({ open: true, period: 'July 2026', userId: targetId })}
          >
            <FileText size={14} /> View Pay Slip
          </button>
          {isAdmin && (
            <button
              className="btn"
              style={{ background: 'rgba(255,255,255,0.15)', color: 'white', border: '1px solid rgba(255,255,255,0.3)', backdropFilter: 'blur(4px)' }}
              onClick={() => handleOpenEdit(targetId)}
            >
              <Edit2 size={14} /> Edit Salary
            </button>
          )}
        </div>
      </div>

      {/* Salary Breakdown + Pay History */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
        {/* Earnings & Deductions */}
        <div className="card">
          <div className="card-header"><span className="card-title">Salary Breakdown</span></div>
          <div className="card-body">
            <div style={{ marginBottom: '1rem' }}>
              <div style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--color-success)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.625rem' }}>Earnings</div>
              {[
                { label: 'Base Salary', value: payrollData.baseSalary },
                { label: 'HRA (House Rent Allowance)', value: payrollData.hra },
                { label: 'Medical Allowance', value: payrollData.medical },
                { label: 'Transport Allowance', value: payrollData.transport },
              ].map(item => (
                <div key={item.label} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.625rem 0', borderBottom: '1px solid var(--color-border-light)' }}>
                  <span style={{ fontSize: '0.875rem', color: 'var(--color-text-secondary)' }}>{item.label}</span>
                  <span style={{ fontWeight: 600, color: 'var(--color-success)', fontSize: '0.875rem' }}>+{sym}{item.value.toLocaleString()}</span>
                </div>
              ))}
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem 0.875rem', background: 'var(--color-success-bg)', borderRadius: 'var(--radius)', marginTop: '0.5rem' }}>
                <span style={{ fontWeight: 600, fontSize: '0.875rem', color: 'var(--color-success)' }}>Gross Earnings</span>
                <span style={{ fontWeight: 700, color: 'var(--color-success)' }}>{sym}{(payrollData.baseSalary + payrollData.hra + payrollData.medical + payrollData.transport).toLocaleString()}</span>
              </div>
            </div>

            <div>
              <div style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--color-danger)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: '0.625rem' }}>Deductions</div>
              {[
                { label: 'Income Tax', value: payrollData.tax },
                { label: 'Provident Fund (PF)', value: payrollData.pf },
              ].map(item => (
                <div key={item.label} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.625rem 0', borderBottom: '1px solid var(--color-border-light)' }}>
                  <span style={{ fontSize: '0.875rem', color: 'var(--color-text-secondary)' }}>{item.label}</span>
                  <span style={{ fontWeight: 600, color: 'var(--color-danger)', fontSize: '0.875rem' }}>−{sym}{item.value.toLocaleString()}</span>
                </div>
              ))}
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem 0.875rem', background: 'var(--color-danger-bg)', borderRadius: 'var(--radius)', marginTop: '0.5rem' }}>
                <span style={{ fontWeight: 600, fontSize: '0.875rem', color: 'var(--color-danger)' }}>Total Deductions</span>
                <span style={{ fontWeight: 700, color: 'var(--color-danger)' }}>−{sym}{(payrollData.tax + payrollData.pf).toLocaleString()}</span>
              </div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', padding: '1rem', background: 'linear-gradient(135deg, #EDE9FE, #DDD6FE)', borderRadius: 'var(--radius)', marginTop: '1rem', border: '1px solid rgba(124,58,237,0.2)' }}>
              <span style={{ fontWeight: 700, color: 'var(--color-primary)' }}>NET SALARY</span>
              <span style={{ fontWeight: 800, fontSize: '1.125rem', color: 'var(--color-primary)' }}>{sym}{payrollData.netSalary.toLocaleString()}</span>
            </div>
          </div>
        </div>

        {/* Pay Slip History */}
        <div className="card">
          <div className="card-header"><span className="card-title">Pay Slip History</span></div>
          <div className="card-body" style={{ padding: 0 }}>
            <table className="table">
              <thead>
                <tr>
                  <th>Period</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {paySlips.map(slip => (
                  <tr key={slip.id}>
                    <td>
                      <div style={{ fontWeight: 500, fontSize: '0.875rem' }}>{slip.period}</div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--color-text-muted)' }}>{slip.paidOn}</div>
                    </td>
                    <td><Badge status={slip.status} /></td>
                    <td>
                      <button
                        className="btn btn-sm btn-outline"
                        onClick={() => handleDownloadPaySlip(slip.period, targetId)}
                      >
                        <Download size={13} /> Download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Edit Payroll Modal (Admin) */}
      <Modal
        open={editPayrollModal.open}
        onClose={() => setEditPayrollModal({ open: false, userId: null })}
        title={`Edit Salary Structure – ${state.users.find(u => u.id === editPayrollModal.userId)?.name}`}
        footer={
          <>
            <button className="btn btn-outline" onClick={() => setEditPayrollModal({ open: false, userId: null })} disabled={editLoading}>Cancel</button>
            <button className="btn btn-primary" onClick={handleSavePayroll} disabled={editLoading}>
              {editLoading ? <span className="spinner" /> : <><Save size={14} /> Save Changes</>}
            </button>
          </>
        }
      >
        <form style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div style={{ padding: '0.75rem', background: 'var(--color-info-bg)', borderRadius: 'var(--radius)', fontSize: '0.875rem', color: 'var(--color-info)' }}>
            ℹ️ Net salary is automatically calculated: (Base + Allowances) − (Tax + PF)
          </div>
          <div className="grid-2">
            <div className="form-group">
              <label className="form-label">Base Salary</label>
              <input type="number" className="form-control" value={editForm.baseSalary || ''} onChange={e => setEditForm(f => ({ ...f, baseSalary: e.target.value }))} />
            </div>
            <div className="form-group">
              <label className="form-label">Currency</label>
              <select className="form-control" value={editForm.currency || 'USD'} onChange={e => setEditForm(f => ({ ...f, currency: e.target.value }))}>
                {['USD', 'INR', 'GBP', 'EUR', 'KRW'].map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">HRA</label>
              <input type="number" className="form-control" value={editForm.hra || ''} onChange={e => setEditForm(f => ({ ...f, hra: e.target.value }))} />
            </div>
            <div className="form-group">
              <label className="form-label">Medical Allowance</label>
              <input type="number" className="form-control" value={editForm.medical || ''} onChange={e => setEditForm(f => ({ ...f, medical: e.target.value }))} />
            </div>
            <div className="form-group">
              <label className="form-label">Transport Allowance</label>
              <input type="number" className="form-control" value={editForm.transport || ''} onChange={e => setEditForm(f => ({ ...f, transport: e.target.value }))} />
            </div>
            <div className="form-group">
              <label className="form-label">Income Tax</label>
              <input type="number" className="form-control" value={editForm.tax || ''} onChange={e => setEditForm(f => ({ ...f, tax: e.target.value }))} />
            </div>
            <div className="form-group">
              <label className="form-label">Provident Fund (PF)</label>
              <input type="number" className="form-control" value={editForm.pf || ''} onChange={e => setEditForm(f => ({ ...f, pf: e.target.value }))} />
            </div>
          </div>
        </form>
      </Modal>

      {/* Pay Slip Preview Modal */}
      <Modal
        open={paySlipModal.open}
        onClose={() => setPaySlipModal({ open: false, period: null, userId: null })}
        title={`Pay Slip – ${paySlipModal.period}`}
        footer={
          <>
            <button className="btn btn-outline" onClick={() => setPaySlipModal({ open: false, period: null, userId: null })}>Close</button>
            <button className="btn btn-primary" onClick={() => handleDownloadPaySlip(paySlipModal.period, paySlipModal.userId)}>
              <Download size={14} /> Download
            </button>
          </>
        }
      >
        {paySlipModal.userId && (() => {
          const u = state.users.find(x => x.id === paySlipModal.userId);
          const p = state.profiles[paySlipModal.userId];
          const pay = state.payroll[paySlipModal.userId];
          const s2 = pay?.currency === 'INR' ? '₹' : pay?.currency === 'GBP' ? '£' : pay?.currency === 'KRW' ? '₩' : '$';
          return (
            <div style={{ fontFamily: 'monospace', background: 'var(--color-surface-2)', padding: '1.5rem', borderRadius: 'var(--radius-lg)', border: '1px solid var(--color-border)' }}>
              <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
                <div style={{ fontWeight: 800, fontSize: '1.25rem', color: 'var(--color-primary)', letterSpacing: '-0.02em' }}>NEXORA HR</div>
                <div style={{ fontSize: '0.875rem', color: 'var(--color-text-muted)', marginTop: '0.25rem' }}>Official Pay Slip · {paySlipModal.period}</div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem', marginBottom: '1rem', fontSize: '0.8125rem' }}>
                <div><span style={{ color: 'var(--color-text-muted)' }}>Employee:</span> <strong>{u?.name}</strong></div>
                <div><span style={{ color: 'var(--color-text-muted)' }}>Emp ID:</span> <strong>{u?.empId}</strong></div>
                <div><span style={{ color: 'var(--color-text-muted)' }}>Department:</span> <strong>{p?.department}</strong></div>
                <div><span style={{ color: 'var(--color-text-muted)' }}>Designation:</span> <strong>{p?.jobTitle}</strong></div>
              </div>
              <div style={{ height: 1, background: 'var(--color-border)', marginBottom: '1rem' }} />
              {[
                { label: 'Base Salary', value: pay?.baseSalary, type: 'earn' },
                { label: 'HRA', value: pay?.hra, type: 'earn' },
                { label: 'Medical Allowance', value: pay?.medical, type: 'earn' },
                { label: 'Transport Allowance', value: pay?.transport, type: 'earn' },
                { label: 'Income Tax', value: pay?.tax, type: 'ded' },
                { label: 'Provident Fund', value: pay?.pf, type: 'ded' },
              ].map(item => (
                <div key={item.label} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.375rem 0', fontSize: '0.8125rem', borderBottom: '1px dashed var(--color-border)' }}>
                  <span style={{ color: 'var(--color-text-secondary)' }}>{item.type === 'earn' ? '+ ' : '− '}{item.label}</span>
                  <span style={{ fontWeight: 600, color: item.type === 'ded' ? 'var(--color-danger)' : 'var(--color-text-primary)' }}>{s2}{item.value?.toLocaleString()}</span>
                </div>
              ))}
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '0.875rem 1rem', background: 'linear-gradient(135deg, #EDE9FE, #DDD6FE)', borderRadius: 'var(--radius)', marginTop: '1rem', border: '1px solid rgba(124,58,237,0.2)' }}>
                <span style={{ fontWeight: 700, color: 'var(--color-primary)', fontSize: '0.9375rem' }}>NET PAY</span>
                <span style={{ fontWeight: 800, fontSize: '1.125rem', color: 'var(--color-primary)' }}>{s2}{pay?.netSalary?.toLocaleString()}</span>
              </div>
            </div>
          );
        })()}
      </Modal>
    </div>
  );
}
